spring:
  application:
    name: cosmic-dust-api

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: "always"

server:
  port: 8080